# ─────────────────────────────────────────
# 인터뷰 순서 규칙 – “심층 위치 자유” 버전
# ─────────────────────────────────────────

# 1) 모든 코드에 공통으로 적용되는 규칙
common:
  # 발표준비 → 발표면접 → 커피챗  핵심 흐름
  - {predecessor: 발표준비 , successor: 발표면접 , min_gap_min: 5}
  - {predecessor: 발표면접 , successor: 커피챗   , min_gap_min: 0}

  # 커피챗은 반드시 마지막
  - {predecessor: 심층면접 , successor: 커피챗   , min_gap_min: 0}

# 2) 코드별 특수 규칙 없음 → 빈 딕셔너리
by_code: {}


# # ─────────────────────────────────────────
# # 0) 재사용 시퀀스 앵커 – “심층면접·커피챗” 버전
# # ─────────────────────────────────────────
# SEQ_DEEP_A: &SEQ_DEEP_A      # 발표준비 → 발표면접 → 심층면접 → 커피챗
#   - {predecessor: 발표준비 , successor: 발표면접 , min_gap_min: 5}
#   - {predecessor: 발표면접 , successor: 심층면접 , min_gap_min: 5}
#   - {predecessor: 심층면접 , successor: 커피챗   , min_gap_min: 5}

# SEQ_DEEP_B: &SEQ_DEEP_B      # 심층면접 → 발표준비 → 발표면접 → 커피챗
#   - {predecessor: 심층면접 , successor: 발표준비 , min_gap_min: 5}
#   - {predecessor: 발표준비 , successor: 발표면접 , min_gap_min: 5}
#   - {predecessor: 발표면접 , successor: 커피챗   , min_gap_min: 5}
# # ── 1) 공통 규칙 (전 코드 공통) ────────────────────────
# common:
#   - {predecessor: 발표준비, successor: 발표면접, min_gap_min: 5}
# # ─────────────────────────────────────────
# # 2) by_code – 신규 규칙만 발췌
# # ─────────────────────────────────────────
# by_code:
#   M01: {default: *SEQ_DEEP_A}
#   M02: {default: *SEQ_DEEP_A}
#   M03: {default: *SEQ_DEEP_A}
#   M04: {A: *SEQ_DEEP_A, B: *SEQ_DEEP_B}
#   M05: {A: *SEQ_DEEP_A, B: *SEQ_DEEP_B}
#   M06: {A: *SEQ_DEEP_A, B: *SEQ_DEEP_B}
#   M07: {A: *SEQ_DEEP_A, B: *SEQ_DEEP_B}
#   M08: {A: *SEQ_DEEP_A, B: *SEQ_DEEP_B}