# ── 0) 재사용용 앵커(Anchor) ──────────────────────────
#     같은 리스트를 여러 코드에 붙여넣지 않기 위해 한 번만 정의
A_SEQ: &A_SEQ               # A-branch : 인성검사 → 토론면접
  - {predecessor: 인성검사 , successor: 토론면접 , min_gap_min: 5}

B_SEQ: &B_SEQ               # B-branch : 토론면접 → 인성검사
  - {predecessor: 토론면접 , successor: 인성검사 , min_gap_min: 5}

# ── 1) 공통 규칙 ───────────────────────────────────────
# 인성검사·토론면접 두 활동만 있으므로, 전체 공통 규칙은 따로 두지 않음
common: []

# ── 2) 코드별 규칙 ────────────────────────────────────
by_code:
  # ── 인성검사만 보는 직무 ───────────────────────────
  AJ01:
    default: []        # 단일 활동이라 선-후행 규칙 없음
  AK01:
    default: []
  AK02:
    default: []
  AL01:
    default: []
  AM07:
    default: []
  AM08:
    default: []
  AM09:
    default: []

  # ── 인성검사 + 토론면접 직무 (A / B branch) ────────
  AM01: {A: *A_SEQ, B: *B_SEQ}
  AM02: {A: *A_SEQ, B: *B_SEQ}
  AM03: {A: *A_SEQ, B: *B_SEQ}
  AM04: {A: *A_SEQ, B: *B_SEQ}
  AM05: {A: *A_SEQ, B: *B_SEQ}
  AM06: {A: *A_SEQ, B: *B_SEQ}
